### ISSUE TITLE
Integrate with CI System

### ISSUE THREAD

**Issue by ereyue** [ereyue/Craft#1]
Currently, the final CSS & JS files are built from `src/` folder manually before tagging and pushing. 

Introduce a new `dev` branch, and working on it. Fire up the CI once the `dev` branch could be merged into the `master` branch, and use CI to generate CSS & JS files.

**Comment by wolther47** [comment]
[Dev](/wolther47/Craft/tree/dev) branch created

**Comment by ereyue** [comment]
CI integration introduced
